services:
  nginx:
    ports: 
      - "85:85"
      - "445:445"
    volumes:
      - ./src/nginx/certbot/www/:/var/www/certbot/:ro
      - ./src/nginx/certbot/conf/:/etc/nginx/ssl/:ro

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./src/nginx/certbot/www/:/var/www/certbot/:rw
  #     - ./src/nginx/certbot/conf/:/etc/letsencrypt/:rw