services:
  nginx:
    ports: 
      - "5173:5173"

  laravel:
    volumes:
      - ./src/xdebug/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts: 
      - host.docker.internal:${HOST_IP:-172.17.0.1}
    
